// generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: Foo */
			nil,       /* empty */
			shift(3),  /* foo */
			reduce(2), /* bar, reduce: Foo */

		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* empty */
			nil,          /* foo */
			nil,          /* bar */

		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: Bar */
			nil,       /* empty */
			nil,       /* foo */
			shift(5),  /* bar */

		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: Foo */
			nil,       /* empty */
			nil,       /* foo */
			reduce(3), /* bar, reduce: Foo */

		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Start */
			nil,       /* empty */
			nil,       /* foo */
			nil,       /* bar */

		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: Bar */
			nil,       /* empty */
			nil,       /* foo */
			nil,       /* bar */

		},
	},
}
