// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0

		-1, // S'
		1,  // Start
		2,  // Foo
		-1, // Bar

	},
	gotoRow{ // S1

		-1, // S'
		-1, // Start
		-1, // Foo
		-1, // Bar

	},
	gotoRow{ // S2

		-1, // S'
		-1, // Start
		-1, // Foo
		4,  // Bar

	},
	gotoRow{ // S3

		-1, // S'
		-1, // Start
		-1, // Foo
		-1, // Bar

	},
	gotoRow{ // S4

		-1, // S'
		-1, // Start
		-1, // Foo
		-1, // Bar

	},
	gotoRow{ // S5

		-1, // S'
		-1, // Start
		-1, // Foo
		-1, // Bar

	},
}
